name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  # PAM username-password obtain required parameter
  app-id:
    description: "Application Id"
    required: true
  user-name:
    description: "Account to be queried"
    required: true
  asset-name:
    description: "Asset name"
    required: true
  request-reason:
    description: "reason for enquiry"
    required: false
    default: "username-password obtain"
  connect-host:
    description: "PAM ip address"
    required: true
  credential-file:
    description: "credential file"
    required: false
    default: "/workspace/cre.cred"
    
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
  goodbye-sh:
    description: "goodbye"
    value: ${{ steps.goodbye.outputs.abc }}
runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo "Hello $INPUT_WHO_TO_GREET."
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}

    - name: echo goodbye
      run: $GITHUB_ACTION_PATH/goodbye.sh
      shell: bash
      env:
        APP_ID: ${{ inputs.app-id }}
        USER_NAME: ${{ inputs.user-name }}
        ASSET_NAME: ${{ inputs.asset-name}}
        REQUEST_REASON: ${{ inputs.request-reason }}
        CONNECT_HOST: ${{ inputs.connect-host }}
        CREDENTIAL_FILE: ${{ inputs.credential-file }}
    - name: echo GITHUB_OUT
      run: cat $GITHUB_OUTPUT
      shell: bash
    - name: echo GITHUB_OUT
      run: echo $(cat $GITHUB_OUTPUT)
      shell: bash
