name: action.yml demo

on: 
  issue_comment:
    types: [created, deleted]
  issues:
    types: [opened, edited, milestoned]
      
jobs:
  hello_world_job:
    runs-on: [self-hosted]
    name: A job to say hello
    outputs:
      username: ${{ steps.foo.outputs.username }}
      password: ${{ steps.foo.outputs.password }}
    steps:
      - id: foo
        uses: heyh-bit/pam-obtain@v72
        with:
          app-id: "test"
          user-name: "root"
          asset-name: "resource"
          request-reason: "demo123456 7890"
          connect-host: "10.13.1.2"
          credential: ${{ secrets.PAM_TOKEN }}
  hello_world_job2:
    runs-on: [self-hosted]
    name: A job to say hello1
    needs: [hello_world_job]
    steps:
      - id: step2
        run: echo $GITHUB_ENV; cat $GITHUB_ENV;
      - id: step3
        run: >
          PASSWORD=$(openssl enc -aes-256-cbc -d -pass pass:YOUR_ENCRYPTION_PASSPHRASE -pbkdf2 -base64 <<< "${{ needs.hello_world_job.outputs.password }}");
          oc create secret generic hello-world
          --from-literal=username=${{ needs.hello_world_job.outputs.username }}
          --from-literal=pawd=$PASSWORD
          --dry-run=client -o yaml -n default | oc replace -f -
