name: action.yml demo

on: 
  issue_comment:
    types: [created, deleted]
  issues:
    types: [opened, edited, milestoned]

jobs:
  hello_world_job:
    runs-on: [self-hosted]
    name: A job to say hello
    steps:
      - id: foo
        uses: heyh-bit/pam-obtain@v50
        with:
          app-id: "test"
          user-name: "root"
          asset-name: "resource"
          request-reason: "demo123456 7890"
          connect-host: "10.13.1.2"
          credential-file: "/workspace/cre.cred"
      - id: step2
        run: |
          echo ${{ steps.foo.outputs.username }};
          echo ${{ steps.foo.outputs.password }}
