name: action.yml demo

on: 
  issue_comment:
    types: [created, deleted]
  issues:
    types: [opened, edited, milestoned]

jobs:
  hello_world_job:
    runs-on: [self-hosted]
    name: A job to say hello
    outputs:
      username: ${{ steps.foo.outputs.username }}
      paswd: ${{ steps.foo.outputs.password }}
    env:
      super_username: ${{ steps.foo.outputs.username }}
      super_password: ${{ steps.foo.outputs.password }}
    steps:
      - id: foo
        uses: heyh-bit/pam-obtain@v60
        with:
          app-id: "test"
          user-name: "root"
          asset-name: "resource"
          request-reason: "demo123456 7890"
          connect-host: "10.13.1.2"
          credential: ${{ secrets.PAM_TOKEN }}
      - id: step2
        run: |
          echo ${{ steps.foo.outputs.username }};
          echo ${{ steps.foo.outputs.password }};
          echo ${{ env.super_username }};
          echo ${{ env.super_password }};          
  hello_world_job2:
    runs-on: [self-hosted]
    name: test env
    steps:
      - id: step1
        name: test
        run: |
          echo ${{ env.super_username }};
          echo ${{ env.super_password }};
