name: action.yml demo

on: 
  issue_comment:
    types: [created, deleted]
  issues:
    types: [opened, edited, milestoned]
      
jobs:
  hello_world_job:
    runs-on: [self-hosted]
    name: A job to say hello
    outputs:
      username: ${{ steps.foo.outputs.username }}
      password: ${{ steps.foo.outputs.password }}
    steps:
      - id: foo
        uses: heyh-bit/pam-obtain@v85
        with:
          app-id: "test"
          user-name: "root"
          asset-name: "resource"
          connect-host: "10.13.1.2"
          credential: ${{ secrets.PAM_TOKEN }}
          encryption-passphrase: ${{ secrets.ENCRYPTION_PASSPHRASE }}
      - id: env
        run: |
          echo $GITHUB_ENV;cat $GITHUB_ENV;
  hello_world_job2:
    runs-on: [self-hosted]
    name: A job to say hello1
    needs: [hello_world_job]
    steps:
      - id: env
        run: |
          echo $GITHUB_ENV;cat $GITHUB_ENV;
      - id: step3
        run: echo "${{ needs.hello_world_job.outputs.username }}"
      - name: Mask Password
        run: |
          API_PASSWORD="${{ needs.hello_world_job.outputs.username }}"
          echo ::add-mask::$API_PASSWORD
          echo API_PASSWORD=$API_PASSWORD >> $GITHUB_ENV
      - id: step2
        name: 修改 secret 值
        run: >
          oc create secret generic ${{ vars.SECRETS_JENKINS }}
          --from-literal=username=hello
          --from-literal=pwd=${{ env.API_PASSWORD }}
          --dry-run=client -o yaml -n default | oc replace -f -
