name: action.yml demo

on: 
  issue_comment:
    types: [created, deleted]
  issues:
    types: [opened, edited, milestoned]
      
jobs:
  hello_world_job:
    runs-on: [self-hosted]
    name: A job to say hello
    outputs:
      username: ${{ steps.foo.outputs.username }}
      password: ${{ steps.foo.outputs.password }}
    steps:
      - id: foo
        uses: heyh-bit/pam-obtain@v81
        with:
          app-id: "test"
          user-name: "root"
          asset-name: "resource"
          connect-host: "10.13.1.2"
          credential: ${{ secrets.PAM_TOKEN }}
          encryption-passphrase: ${{ secrets.ENCRYPTION_PASSPHRASE }}
  hello_world_job2:
    runs-on: [self-hosted]
    name: A job to say hello1
    needs: [hello_world_job]
    steps:
      - id: step3
        run: echo "::add-mask::${{ needs.hello_world_job.outputs.password }}"
      - id: step4
        run: echo "${{ needs.hello_world_job.outputs.password }}"
