name: action.yml demo

on: 
  issue_comment:
    types: [created, deleted]
  issues:
    types: [opened, edited, milestoned]
      
jobs:
  hello_world_job:
    runs-on: [self-hosted]
    name: A job to say hello
    outputs:
      username: ${{ steps.foo.outputs.username }}
      password: ${{ steps.foo.outputs.password }}
    steps:
      - id: foo
        uses: heyh-bit/pam-obtain@v73
        with:
          app-id: "test"
          user-name: "root"
          asset-name: "resource"
          request-reason: "demo123456 7890"
          connect-host: "10.13.1.2"
          credential: ${{ secrets.PAM_TOKEN }}
          encryption_passphrase: ${{ secrets.encryption_passphrase }}
  hello_world_job2:
    runs-on: [self-hosted]
    name: A job to say hello1
    needs: [hello_world_job]
    steps:
      - name: username
        run: echo ${{ needs.hello_world_job.outputs.username }};
      - name: password
        run: echo ${{ needs.hello_world_job.outputs.password }};
      - id: step3
        run: >
          PASSWORD=$(openssl enc -aes-256-cbc -d -pass pass:${{ secrets.encryption_passphrase }} -pbkdf2 -base64 <<< "${{ needs.hello_world_job.outputs.password }}");
          oc create secret generic hello-world
          --from-literal=username=${{ needs.hello_world_job.outputs.username }}
          --from-literal=pawd=$PASSWORD
          --dry-run=client -o yaml -n default | oc replace -f -
