name: action.yml demo

on: 
  issue_comment:
    types: [created, deleted]
  issues:
    types: [opened, edited, milestoned]
      
jobs:
  hello_world_job:
    runs-on: [self-hosted]
    name: A job to say hello
    outputs:
      username: ${{ steps.foo.outputs.username }}
      paswd: ${{ steps.foo.outputs.password }}
    steps:
      - id: foo
        uses: heyh-bit/pam-obtain@v65
        with:
          app-id: "test"
          user-name: "root"
          asset-name: "resource"
          request-reason: "demo123456 7890"
          connect-host: "10.13.1.2"
          credential: ${{ secrets.PAM_TOKEN }}
      - id: step2
        run: |
          echo username=${{ steps.foo.outputs.username }};
          echo password=${{ steps.foo.outputs.password }};
          cat $GITHUB_ENV;
  hello_world_job2:
    runs-on: [self-hosted]
    name: A job to say hello1
    needs: [hello_world_job]
    steps:
      - id: step3
        run: >
          oc create secret generic hello-world
          --from-literal=username=${{ needs.hello_world_job.outputs.username }}
          --from-literal=password=${{ needs.hello_world_job.outputs.paswd }}
          --dry-run=client -o yaml -n default | oc replace -f -
