name: action.yml demo

on: 
  issue_comment:
    types: [created, deleted]
  issues:
    types: [opened, edited, milestoned]

jobs:
  hello_world_job:
    runs-on: [self-hosted]
    name: A job to say hello
    steps:
      - id: foo
        uses: heyh-bit/pam-obtain@v34
        with:
          app-id: "test"
          user-name: ${{ secrets.USERNAME1 }}
          asset-name: ${{ secrets.ASSETNAME1 }}
          requiest-reason: "test demo123456"
          connect-host: "10.13.1.2"
          credential-file: "/workspace/cre.cred"
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.username-password }}
