name: Secure Information Transfer

on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Set an environment variable
      run: echo "MY_VAR=Hello" >> $GITHUB_ENV
 
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: Use the environment variable
      run: echo "${{ env.MY_VAR }}"
