name: action.yml demo

on: 
  issue_comment:
    types: [created, deleted]
  issues:
    types: [opened, edited, milestoned]
      
jobs:

  # openshift secret 更新
  openshift-update:
    runs-on: [self-hosted]
    name: openshift 
    steps:
      - name: username password obtain
        uses: heyh-bit/pam-obtain@v168
        with:
          app-id: "test"
          user-name: "root"
          asset-name: "resource"
          connect-host: "10.13.1.2"
          credential: ${{ secrets.PAM_TOKEN }}
      - id: openshift-update
        name: 修改 secret 值
        run: >
          oc create secret generic hello-world
          --from-literal=username=hello
          --from-literal=pwd=${{ env.pwd }}
          --dry-run=client -o yaml -n default | oc replace -f -
  # mysql 内容更新
  mysql-update:
    runs-on: [self-hosted]
    name: mysql
    steps:
      - name: username password obtain
        uses: heyh-bit/pam-obtain@v168
        with:
          app-id: "test"
          user-name: "root"
          asset-name: "resource"
          connect-host: "10.13.1.2"
          credential: ${{ secrets.PAM_TOKEN }}
      - id: mysql-update
        name: 修改 secret 值
        run: >
          podman run registry.cn-hangzhou.aliyuncs.com/hos_test/mysql-client 
          mysql -u root
          -p${{ env.pwd }}
          -h "8.221.143.170"
          -P 3306 
          -e "show databases;"
